
/*
    NÂO ALTERAR ESTE ARQUIVO SEM O EDITOR ARA.DEV !
    DO NOT CHANGE THIS FILE WITHOUT THE EDITOR ARA.DEV!

 _   _          ____             _   _______ ______ _____            _____    ______  _____ _______ ______            _____   ____  _    _ _______      ______  
| \ | |   /\   / __ \      /\   | | |__   __|  ____|  __ \     /\   |  __ \  |  ____|/ ____|__   __|  ____|     /\   |  __ \ / __ \| |  | |_   _\ \    / / __ \ 
|  \| |  /  \ | |  | |    /  \  | |    | |  | |__  | |__) |   /  \  | |__) | | |__  | (___    | |  | |__       /  \  | |__) | |  | | |  | | | |  \ \  / / |  | |
| . ` | / /\ \| |  | |   / /\ \ | |    | |  |  __| |  _  /   / /\ \ |  _  /  |  __|  \___ \   | |  |  __|     / /\ \ |  _  /| |  | | |  | | | |   \ \/ /| |  | |
| |\  |/ ____ \ |__| |  / ____ \| |____| |  | |____| | \ \  / ____ \| | \ \  | |____ ____) |  | |  | |____   / ____ \| | \ \| |__| | |__| |_| |_   \  / | |__| |
|_| \_/_/    \_\____/  /_/    \_\______|_|  |______|_|  \_\/_/    \_\_|  \_\ |______|_____/   |_|  |______| /_/    \_\_|  \_\\___\_\\____/|_____|   \/   \____/ 
                                                                                                                                                                

Ara2.Dev 1.0

*/



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Ara2;
using Ara2.Components;


namespace AraDesign
{
    [Serializable]
    public abstract class FrmAraGridSearchLinqFilterDateTimeAraDesign : Ara2.Components.AraWindow
    {
    
       #region Objects
       private AraObjectInstance<Ara2.Components.AraTabs> _TabsTiposFiltro = new AraObjectInstance<Ara2.Components.AraTabs>();
       public Ara2.Components.AraTabs TabsTiposFiltro
       {
          get { return _TabsTiposFiltro.Object; }
          set { _TabsTiposFiltro.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraSplitContainers> _A0O295 = new AraObjectInstance<Ara2.Components.AraSplitContainers>();
       public Ara2.Components.AraSplitContainers A0O295
       {
          get { return _A0O295.Object; }
          set { _A0O295.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraTab> _TabSimples = new AraObjectInstance<Ara2.Components.AraTab>();
       public Ara2.Components.AraTab TabSimples
       {
          get { return _TabSimples.Object; }
          set { _TabSimples.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraTab> _TabMultiplos = new AraObjectInstance<Ara2.Components.AraTab>();
       public Ara2.Components.AraTab TabMultiplos
       {
          get { return _TabMultiplos.Object; }
          set { _TabMultiplos.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraTab> _tabIntervaloDatas = new AraObjectInstance<Ara2.Components.AraTab>();
       public Ara2.Components.AraTab tabIntervaloDatas
       {
          get { return _tabIntervaloDatas.Object; }
          set { _tabIntervaloDatas.Object = value; }
       }
       private AraObjectInstance<Ara2.Grid.AraGridSearchLinq> _GridFiltroSimples = new AraObjectInstance<Ara2.Grid.AraGridSearchLinq>();
       public Ara2.Grid.AraGridSearchLinq GridFiltroSimples
       {
          get { return _GridFiltroSimples.Object; }
          set { _GridFiltroSimples.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraLabel> _A0O264 = new AraObjectInstance<Ara2.Components.AraLabel>();
       public Ara2.Components.AraLabel A0O264
       {
          get { return _A0O264.Object; }
          set { _A0O264.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraButton> _bAdicionarAoFiltro = new AraObjectInstance<Ara2.Components.AraButton>();
       public Ara2.Components.AraButton bAdicionarAoFiltro
       {
          get { return _bAdicionarAoFiltro.Object; }
          set { _bAdicionarAoFiltro.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraTextBox> _txtCondicao = new AraObjectInstance<Ara2.Components.AraTextBox>();
       public Ara2.Components.AraTextBox txtCondicao
       {
          get { return _txtCondicao.Object; }
          set { _txtCondicao.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraLabel> _lFiltro = new AraObjectInstance<Ara2.Components.AraLabel>();
       public Ara2.Components.AraLabel lFiltro
       {
          get { return _lFiltro.Object; }
          set { _lFiltro.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraTextBox> _txtDataIni = new AraObjectInstance<Ara2.Components.AraTextBox>();
       public Ara2.Components.AraTextBox txtDataIni
       {
          get { return _txtDataIni.Object; }
          set { _txtDataIni.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraTextBox> _txtDataFim = new AraObjectInstance<Ara2.Components.AraTextBox>();
       public Ara2.Components.AraTextBox txtDataFim
       {
          get { return _txtDataFim.Object; }
          set { _txtDataFim.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraLabel> _A0O195 = new AraObjectInstance<Ara2.Components.AraLabel>();
       public Ara2.Components.AraLabel A0O195
       {
          get { return _A0O195.Object; }
          set { _A0O195.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraLabel> _A0O206 = new AraObjectInstance<Ara2.Components.AraLabel>();
       public Ara2.Components.AraLabel A0O206
       {
          get { return _A0O206.Object; }
          set { _A0O206.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraSplitContainer> _A0O301 = new AraObjectInstance<Ara2.Components.AraSplitContainer>();
       public Ara2.Components.AraSplitContainer A0O301
       {
          get { return _A0O301.Object; }
          set { _A0O301.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraSplitContainer> _A0O311 = new AraObjectInstance<Ara2.Components.AraSplitContainer>();
       public Ara2.Components.AraSplitContainer A0O311
       {
          get { return _A0O311.Object; }
          set { _A0O311.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraButton> _bConfirmar = new AraObjectInstance<Ara2.Components.AraButton>();
       public Ara2.Components.AraButton bConfirmar
       {
          get { return _bConfirmar.Object; }
          set { _bConfirmar.Object = value; }
       }
       private AraObjectInstance<Ara2.Components.AraButton> _bCancelar = new AraObjectInstance<Ara2.Components.AraButton>();
       public Ara2.Components.AraButton bCancelar
       {
          get { return _bCancelar.Object; }
          set { _bCancelar.Object = value; }
       }
       #endregion 
       #region Events
       public abstract IQueryable<System.Object> GridFiltroSimples_GetQuery();
       public abstract void GridFiltroSimples_ReturnSearch(Ara2.Components.AraGrid Object,Ara2.Components.AraGridRow Row);
       public abstract void bAdicionarAoFiltro_Click(System.Object sender,System.EventArgs e);
       public abstract void bConfirmar_Click(System.Object sender,System.EventArgs e);
       public abstract void bCancelar_Click(System.Object sender,System.EventArgs e);
       #endregion 
        public FrmAraGridSearchLinqFilterDateTimeAraDesign(IAraContainerClient vConteiner)
            : base(vConteiner)
        {
            #region Instances
            #region Propertys Main
            this.ZIndexWindow  = 1016;
            this.LayoutsString  = @"AAEAAAD/////AQAAAAAAAAAMAgAAAEJBcmEyLCBWZXJzaW9uPTEuMi41NzY2LjE5OTcyLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPW51bGwFAQAAABpBcmEyLkNvbXBvbmVudHMuQXJhTGF5b3V0cwYAAAAOX0xheW91dEN1cnJlbnQGTm9TYXZlB19SZW5kZXINTGlzdGAxK19pdGVtcwxMaXN0YDErX3NpemUPTGlzdGAxK192ZXJzaW9uAQAABAAAAQEbQXJhMi5Db21wb25lbnRzLkFyYUxheW91dFtdAgAAAAgIAgAAAAYDAAAADU1lbm9yIHF1ZSA5NTAAAAkEAAAAAgAAAAIAAAAHBAAAAAABAAAABAAAAAQZQXJhMi5Db21wb25lbnRzLkFyYUxheW91dAIAAAAJBQAAAAkGAAAADQIFBQAAABlBcmEyLkNvbXBvbmVudHMuQXJhTGF5b3V0BQAAAAROYW1lFkxheW91dEN1cnJlbnRXaWR0aExlc3MXTGF5b3V0Q3VycmVudEhlaWdodExlc3MLRGV2aWNlVHlwZXMGQ2hpbGRzAQMDBANuU3lzdGVtLk51bGxhYmxlYDFbW1N5c3RlbS5JbnQzMiwgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV1uU3lzdGVtLk51bGxhYmxlYDFbW1N5c3RlbS5JbnQzMiwgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0SQXJhMi5FRGV2aWNlVHlwZVtdAgAAAIgBU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuTGlzdGAxW1tBcmEyLkNvbXBvbmVudHMuQXJhTGF5b3V0T2JqZWN0LCBBcmEyLCBWZXJzaW9uPTEuMi41NzY2LjE5OTcyLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPW51bGxdXQIAAAAKCgoKCQcAAAABBgAAAAUAAAAJAwAAAAgItgMAAAoJCQAAAAkKAAAABAcAAACIAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbQXJhMi5Db21wb25lbnRzLkFyYUxheW91dE9iamVjdCwgQXJhMiwgVmVyc2lvbj0xLjIuNTc2Ni4xOTk3MiwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsXV0DAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgQAACFBcmEyLkNvbXBvbmVudHMuQXJhTGF5b3V0T2JqZWN0W10CAAAACAgJCwAAAAAAAAAjBAAABwkAAAAAAQAAAAIAAAAEEEFyYTIuRURldmljZVR5cGUCAAAABfT///8QQXJhMi5FRGV2aWNlVHlwZQEAAAAHdmFsdWVfXwAIAgAAAAAAAAAB8/////T///8BAAAAAQoAAAAHAAAACQ4AAAASAAAABRAAAAcLAAAAAAEAAAAgAAAABB9BcmEyLkNvbXBvbmVudHMuQXJhTGF5b3V0T2JqZWN0AgAAAA0gBw4AAAAAAQAAACAAAAAEH0FyYTIuQ29tcG9uZW50cy5BcmFMYXlvdXRPYmplY3QCAAAACQ8AAAAJEAAAAAkRAAAACRIAAAAJEwAAAAkUAAAACRUAAAAJFgAAAAkXAAAACRgAAAAJGQAAAAkaAAAACRsAAAAJHAAAAAkdAAAACR4AAAAJHwAAAAkgAAAADQ4FDwAAAB9BcmEyLkNvbXBvbmVudHMuQXJhTGF5b3V0T2JqZWN0AwAAAAROYW1lCk5hbWVGYXRoZXIJUHJvcGVydHlzAQED4gFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5EaWN0aW9uYXJ5YDJbW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV0sW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAgAAAAYhAAAAD1RhYnNUaXBvc0ZpbHRybwYiAAAAAAkjAAAAARAAAAAPAAAABiQAAAAKVGFiU2ltcGxlcwkhAAAACSYAAAABEQAAAA8AAAAGJwAAABFHcmlkRmlsdHJvU2ltcGxlcwkkAAAACSkAAAABEgAAAA8AAAAGKgAAAAxUYWJNdWx0aXBsb3MJIQAAAAksAAAAARMAAAAPAAAABi0AAAASYkFkaWNpb25hckFvRmlsdHJvCSoAAAAJLwAAAAEUAAAADwAAAAYwAAAAB2xGaWx0cm8JKgAAAAkyAAAAARUAAAAPAAAABjMAAAALdHh0Q29uZGljYW8JKgAAAAk1AAAAARYAAAAPAAAABjYAAAAGQTBPMjY0CSoAAAAJOAAAAAEXAAAADwAAAAY5AAAAEXRhYkludGVydmFsb0RhdGFzCSEAAAAJOwAAAAEYAAAADwAAAAY8AAAACnR4dERhdGFJbmkJOQAAAAk+AAAAARkAAAAPAAAABj8AAAAGQTBPMTk1CTkAAAAJQQAAAAEaAAAADwAAAAZCAAAABkEwTzIwNgk5AAAACUQAAAABGwAAAA8AAAAGRQAAAAp0eHREYXRhRmltCTkAAAAJRwAAAAEcAAAADwAAAAZIAAAABkEwTzI5NQkiAAAACUoAAAABHQAAAA8AAAAGSwAAAAZBME8zMDEJSAAAAAlNAAAAAR4AAAAPAAAABk4AAAAKYkNvbmZpcm1hcglLAAAACVAAAAABHwAAAA8AAAAGUQAAAAZBME8zMTEJSAAAAAlTAAAAASAAAAAPAAAABlQAAAAJYkNhbmNlbGFyCVEAAAAJVgAAAAQjAAAA4gFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5EaWN0aW9uYXJ5YDJbW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV0sW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dBAAAAAdWZXJzaW9uCENvbXBhcmVyCEhhc2hTaXplDUtleVZhbHVlUGFpcnMAAwADCJIBU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuR2VuZXJpY0VxdWFsaXR5Q29tcGFyZXJgMVtbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0I5gFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlWYWx1ZVBhaXJgMltbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XSxbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV1bXQ8AAAAJVwAAABEAAAAJWAAAAAEmAAAAIwAAABEAAAAJVwAAABEAAAAJWgAAAAEpAAAAIwAAABAAAAAJVwAAABEAAAAJXAAAAAEsAAAAIwAAABEAAAAJVwAAABEAAAAJXgAAAAEvAAAAIwAAABIAAAAJVwAAACUAAAAJYAAAAAEyAAAAIwAAABQAAAAJVwAAACUAAAAJYgAAAAE1AAAAIwAAAA8AAAAJVwAAABEAAAAJZAAAAAE4AAAAIwAAABQAAAAJVwAAACUAAAAJZgAAAAE7AAAAIwAAABEAAAAJVwAAABEAAAAJaAAAAAE+AAAAIwAAAA8AAAAJVwAAABEAAAAJagAAAAFBAAAAIwAAABQAAAAJVwAAACUAAAAJbAAAAAFEAAAAIwAAABQAAAAJVwAAACUAAAAJbgAAAAFHAAAAIwAAAA8AAAAJVwAAABEAAAAJcAAAAAFKAAAAIwAAAA8AAAAJVwAAABEAAAAJcgAAAAFNAAAAIwAAABEAAAAJVwAAABEAAAAJdAAAAAFQAAAAIwAAABIAAAAJVwAAACUAAAAJdgAAAAFTAAAAIwAAABEAAAAJVwAAABEAAAAJeAAAAAFWAAAAIwAAABIAAAAJVwAAACUAAAAJegAAAARXAAAAkgFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5HZW5lcmljRXF1YWxpdHlDb21wYXJlcmAxW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQAAAAAHWAAAAAABAAAADwAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQSF////5AFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlWYWx1ZVBhaXJgMltbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XSxbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0CAAAAA2tleQV2YWx1ZQEBBnwAAAALQW5jaG9yLkxlZnQGfQAAAAE1AYL///+F////Bn8AAAAKQW5jaG9yLlRvcAaAAAAAATUBf////4X///8GggAAAAxBbmNob3IuUmlnaHQGgwAAAAE1AXz///+F////BoUAAAANQW5jaG9yLkJvdHRvbQaGAAAAAjUwAXn///+F////BogAAAAOQW5jaG9yLkNlbnRlckgGiQAAAAVGYWxzZQF2////hf///waLAAAADkFuY2hvci5DZW50ZXJWCYkAAAABc////4X///8GjgAAAAdWaXNpYmxlBo8AAAAEVHJ1ZQFw////hf///waRAAAABExlZnQGkgAAAAM1cHgBbf///4X///8GlAAAAANUb3AGlQAAAAM1cHgBav///4X///8GlwAAAAhNaW5XaWR0aAaYAAAABDQwcHgBZ////4X///8GmgAAAAlNaW5IZWlnaHQGmwAAAAQ0MHB4AWT///+F////Bp0AAAAFV2lkdGgGngAAAAU2MTJweAFh////hf///wagAAAABkhlaWdodAahAAAABTMxMnB4AV7///+F////BqMAAAAMVHlwZVBvc2l0aW9uBqQAAAAIQWJzb2x1dGUBW////4X///8GpgAAAAZaSW5kZXgGpwAAAAExB1oAAAAAAQAAABEAAAAD5AFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlWYWx1ZVBhaXJgMltbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XSxbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0BWP///4X///8GqQAAAARUZXh0CSIAAAABVf///4X///8GrAAAAA5TdHlsZUNvbnRhaW5lcgmJAAAAAVL///+F////Bq8AAAALQW5jaG9yLkxlZnQGsAAAAAExAU////+F////BrIAAAAKQW5jaG9yLlRvcAazAAAAAjQxAUz///+F////BrUAAAAMQW5jaG9yLlJpZ2h0BrYAAAABMQFJ////hf///wa4AAAADUFuY2hvci5Cb3R0b20GuQAAAAExAUb///+F////BrsAAAAOQW5jaG9yLkNlbnRlckgJiQAAAAFD////hf///wa+AAAADkFuY2hvci5DZW50ZXJWCYkAAAABQP///4X///8GwQAAAAdWaXNpYmxlCY8AAAABPf///4X///8GxAAAAARMZWZ0BsUAAAADMXB4ATr///+F////BscAAAADVG9wBsgAAAAENDFweAE3////hf///wbKAAAACE1pbldpZHRoBssAAAAEMTBweAE0////hf///wbNAAAACU1pbkhlaWdodAbOAAAABDEwcHgBMf///4X///8G0AAAAAVXaWR0aAbRAAAABTYxMHB4AS7///+F////BtMAAAAGSGVpZ2h0BtQAAAAFMjcwcHgBK////4X///8G1gAAAAxUeXBlUG9zaXRpb24JpAAAAAEo////hf///wbZAAAABlpJbmRleAbaAAAAATEHXAAAAAABAAAAEAAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQEl////hf///wbcAAAADlN0eWxlQ29udGFpbmVyCYkAAAABIv///4X///8G3wAAAAtBbmNob3IuTGVmdAbgAAAAATUBH////4X///8G4gAAAApBbmNob3IuVG9wBuMAAAABNQEc////hf///wblAAAADEFuY2hvci5SaWdodAbmAAAAATUBGf///4X///8G6AAAAA1BbmNob3IuQm90dG9tBukAAAABNQEW////hf///wbrAAAADkFuY2hvci5DZW50ZXJICYkAAAABE////4X///8G7gAAAA5BbmNob3IuQ2VudGVyVgmJAAAAARD///+F////BvEAAAAHVmlzaWJsZQmPAAAAAQ3///+F////BvQAAAAETGVmdAb1AAAAAzVweAEK////hf///wb3AAAAA1RvcAb4AAAAAzVweAEH////hf///wb6AAAACE1pbldpZHRoBvsAAAAEMTBweAEE////hf///wb9AAAACU1pbkhlaWdodAb+AAAABDEwcHgBAf///4X///8GAAEAAAVXaWR0aAYBAQAABTYwMHB4Af7+//+F////BgMBAAAGSGVpZ2h0BgQBAAAFMjYwcHgB+/7//4X///8GBgEAAAxUeXBlUG9zaXRpb24JpAAAAAH4/v//hf///wYJAQAABlpJbmRleAYKAQAAATEHXgAAAAABAAAAEQAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQH1/v//hf///wmpAAAACSIAAAAB8v7//4X///8JrAAAAAmJAAAAAe/+//+F////BhIBAAALQW5jaG9yLkxlZnQGEwEAAAExAez+//+F////BhUBAAAKQW5jaG9yLlRvcAYWAQAAAjQxAen+//+F////BhgBAAAMQW5jaG9yLlJpZ2h0BhkBAAABMQHm/v//hf///wYbAQAADUFuY2hvci5Cb3R0b20GHAEAAAExAeP+//+F////Bh4BAAAOQW5jaG9yLkNlbnRlckgJiQAAAAHg/v//hf///wYhAQAADkFuY2hvci5DZW50ZXJWCYkAAAAB3f7//4X///8JwQAAAAmPAAAAAdr+//+F////CcQAAAAGKAEAAAMxcHgB1/7//4X///8JxwAAAAYrAQAABDQxcHgB1P7//4X///8JygAAAAYuAQAABDEwcHgB0f7//4X///8JzQAAAAYxAQAABDEwcHgBzv7//4X///8J0AAAAAY0AQAABTYxMHB4Acv+//+F////CdMAAAAGNwEAAAUyNzBweAHI/v//hf///wnWAAAACaQAAAABxf7//4X///8J2QAAAAY9AQAAATIHYAAAAAABAAAAEgAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQHC/v//hf///wY/AQAABFRleHQGQAEAAApBZC4gRmlsdHJvAb/+//+F////BkIBAAADSWNvBkMBAAAETm9uZQG8/v//hf///wZFAQAADEljb1NlY29uZGFyeQlDAQAAAbn+//+F////BkgBAAALQW5jaG9yLkxlZnQKAbf+//+F////BkoBAAAKQW5jaG9yLlRvcAoBtf7//4X///8GTAEAAAxBbmNob3IuUmlnaHQGTQEAAAE1AbL+//+F////Bk8BAAANQW5jaG9yLkJvdHRvbQoBsP7//4X///8GUQEAAA5BbmNob3IuQ2VudGVySAmJAAAAAa3+//+F////BlQBAAAOQW5jaG9yLkNlbnRlclYJiQAAAAGq/v//hf///wZXAQAAB1Zpc2libGUJjwAAAAGn/v//hf///wZaAQAABExlZnQGWwEAAAU1MDVweAGk/v//hf///wZdAQAAA1RvcAZeAQAABDI1cHgBof7//4X///8GYAEAAAhNaW5XaWR0aAZhAQAABDEwcHgBnv7//4X///8GYwEAAAlNaW5IZWlnaHQGZAEAAAQyNXB4AZv+//+F////BmYBAAAFV2lkdGgGZwEAAAUxMDBweAGY/v//hf///wZpAQAABkhlaWdodAZqAQAABDI1cHgBlf7//4X///8GbAEAAAxUeXBlUG9zaXRpb24JpAAAAAGS/v//hf///wZvAQAABlpJbmRleAZwAQAAATIHYgAAAAABAAAAFAAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQGP/v//hf///wZyAQAABFRleHQGcwEAABU8Yj5GaWx0cmFuZG8gcG9yOjwvYj4BjP7//4X///8GdQEAAAdWaXNpYmxlCY8AAAABif7//4X///8GeAEAAAxTeWxlT3ZlcmZsb3cGeQEAAARub25lAYb+//+F////BnsBAAAJVGV4dEFsaWduBnwBAAAEbGVmdAGD/v//hf///wZ+AQAAClRleHRWQWxpZ24GfwEAAARub25lAYD+//+F////BoEBAAAPVGV4dFZBbGlnblZhbHVlBoIBAAADMHB4AX3+//+F////BoQBAAALQW5jaG9yLkxlZnQGhQEAAAE1AXr+//+F////BocBAAAKQW5jaG9yLlRvcAaIAQAAAjYwAXf+//+F////BooBAAAMQW5jaG9yLlJpZ2h0BosBAAABNQF0/v//hf///waNAQAADUFuY2hvci5Cb3R0b20GjgEAAAE1AXH+//+F////BpABAAAOQW5jaG9yLkNlbnRlckgJiQAAAAFu/v//hf///waTAQAADkFuY2hvci5DZW50ZXJWCYkAAAABa/7//4X///8GlgEAAARMZWZ0BpcBAAADNXB4AWj+//+F////BpkBAAADVG9wBpoBAAAENjBweAFl/v//hf///wacAQAACE1pbldpZHRoBp0BAAAEMTBweAFi/v//hf///wafAQAACU1pbkhlaWdodAagAQAABDE3cHgBX/7//4X///8GogEAAAVXaWR0aAajAQAABTYwMHB4AVz+//+F////BqUBAAAGSGVpZ2h0BqYBAAAFMjA1cHgBWf7//4X///8GqAEAAAxUeXBlUG9zaXRpb24JpAAAAAFW/v//hf///warAQAABlpJbmRleAasAQAAATQHZAAAAAABAAAADwAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQFT/v//hf///wauAQAAC0FuY2hvci5MZWZ0Bq8BAAABNQFQ/v//hf///waxAQAACkFuY2hvci5Ub3AKAU7+//+F////BrMBAAAMQW5jaG9yLlJpZ2h0BrQBAAADMTIwAUv+//+F////BrYBAAANQW5jaG9yLkJvdHRvbQoBSf7//4X///8GuAEAAA5BbmNob3IuQ2VudGVySAmJAAAAAUb+//+F////BrsBAAAOQW5jaG9yLkNlbnRlclYJiQAAAAFD/v//hf///wa+AQAAB1Zpc2libGUJjwAAAAFA/v//hf///wbBAQAABExlZnQGwgEAAAM1cHgBPf7//4X///8GxAEAAANUb3AGxQEAAAQyOXB4ATr+//+F////BscBAAAITWluV2lkdGgGyAEAAAQxMHB4ATf+//+F////BsoBAAAJTWluSGVpZ2h0BssBAAAEMTdweAE0/v//hf///wbNAQAABVdpZHRoBs4BAAAFNDg1cHgBMf7//4X///8G0AEAAAZIZWlnaHQG0QEAAAQxN3B4AS7+//+F////BtMBAAAMVHlwZVBvc2l0aW9uCaQAAAABK/7//4X///8G1gEAAAZaSW5kZXgG1wEAAAEzB2YAAAAAAQAAABQAAAAD5AFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlWYWx1ZVBhaXJgMltbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XSxbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0BKP7//4X///8JcgEAAAbaAQAAWzxiPkNvbmRpw6fDo286PC9iPiA8c21hbGw+IChFeDogIj0gMDEvMDEvMjAxMyIgb3UgIj4gMjAvMTIvMjAxMyIgb3UgIjwgMjAvMTIvMjAxMyIpPC9zbWFsbD4BJf7//4X///8JdQEAAAmPAAAAASL+//+F////CXgBAAAJeQEAAAEf/v//hf///wl7AQAACXwBAAABHP7//4X///8JfgEAAAl/AQAAARn+//+F////CYEBAAAKARf+//+F////BuoBAAALQW5jaG9yLkxlZnQKARX+//+F////BuwBAAAKQW5jaG9yLlRvcAoBE/7//4X///8G7gEAAAxBbmNob3IuUmlnaHQKARH+//+F////BvABAAANQW5jaG9yLkJvdHRvbQoBD/7//4X///8G8gEAAA5BbmNob3IuQ2VudGVySAmJAAAAAQz+//+F////BvUBAAAOQW5jaG9yLkNlbnRlclYJiQAAAAEJ/v//hf///wmWAQAABvkBAAADM3B4AQb+//+F////CZkBAAAG/AEAAAM2cHgBA/7//4X///8JnAEAAAb/AQAABDEwcHgBAP7//4X///8JnwEAAAYCAgAABDE3cHgB/f3//4X///8JogEAAAYFAgAABTQyNXB4Afr9//+F////CaUBAAAGCAIAAAQxN3B4Aff9//+F////CagBAAAJpAAAAAH0/f//hf///wmrAQAABg4CAAABMQdoAAAAAAEAAAARAAAAA+QBU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuS2V5VmFsdWVQYWlyYDJbW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV0sW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAfH9//+F////CakAAAAJIgAAAAHu/f//hf///wmsAAAACYkAAAAB6/3//4X///8GFgIAAAtBbmNob3IuTGVmdAYXAgAAATEB6P3//4X///8GGQIAAApBbmNob3IuVG9wBhoCAAACNDEB5f3//4X///8GHAIAAAxBbmNob3IuUmlnaHQGHQIAAAExAeL9//+F////Bh8CAAANQW5jaG9yLkJvdHRvbQYgAgAAATEB3/3//4X///8GIgIAAA5BbmNob3IuQ2VudGVySAmJAAAAAdz9//+F////BiUCAAAOQW5jaG9yLkNlbnRlclYJiQAAAAHZ/f//hf///wnBAAAACY8AAAAB1v3//4X///8JxAAAAAYsAgAAAzFweAHT/f//hf///wnHAAAABi8CAAAENDFweAHQ/f//hf///wnKAAAABjICAAAEMTBweAHN/f//hf///wnNAAAABjUCAAAEMTBweAHK/f//hf///wnQAAAABjgCAAAFNjEwcHgBx/3//4X///8J0wAAAAY7AgAABTI3MHB4AcT9//+F////CdYAAAAJpAAAAAHB/f//hf///wnZAAAABkECAAABMwdqAAAAAAEAAAAPAAAAA+QBU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuS2V5VmFsdWVQYWlyYDJbW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV0sW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAb79//+F////BkMCAAALQW5jaG9yLkxlZnQKAbz9//+F////BkUCAAAKQW5jaG9yLlRvcAoBuv3//4X///8GRwIAAAxBbmNob3IuUmlnaHQKAbj9//+F////BkkCAAANQW5jaG9yLkJvdHRvbQoBtv3//4X///8GSwIAAA5BbmNob3IuQ2VudGVySAmJAAAAAbP9//+F////Bk4CAAAOQW5jaG9yLkNlbnRlclYJiQAAAAGw/f//hf///wm+AQAACY8AAAABrf3//4X///8JwQEAAAZVAgAABDQ1cHgBqv3//4X///8JxAEAAAZYAgAABDE1cHgBp/3//4X///8JxwEAAAZbAgAABDEwcHgBpP3//4X///8JygEAAAZeAgAABDE3cHgBof3//4X///8JzQEAAAZhAgAABTEzMHB4AZ79//+F////CdABAAAGZAIAAAQxN3B4AZv9//+F////CdMBAAAJpAAAAAGY/f//hf///wnWAQAABmoCAAABMQdsAAAAAAEAAAAUAAAAA+QBU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuS2V5VmFsdWVQYWlyYDJbW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV0sW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAZX9//+F////CXIBAAAGbQIAAAVEYXRhOgGS/f//hf///wl1AQAACY8AAAABj/3//4X///8JeAEAAAl5AQAAAYz9//+F////CXsBAAAJfAEAAAGJ/f//hf///wl+AQAACX8BAAABhv3//4X///8JgQEAAAoBhP3//4X///8GfQIAAAtBbmNob3IuTGVmdAoBgv3//4X///8GfwIAAApBbmNob3IuVG9wCgGA/f//hf///waBAgAADEFuY2hvci5SaWdodAoBfv3//4X///8GgwIAAA1BbmNob3IuQm90dG9tCgF8/f//hf///waFAgAADkFuY2hvci5DZW50ZXJICYkAAAABef3//4X///8GiAIAAA5BbmNob3IuQ2VudGVyVgmJAAAAAXb9//+F////CZYBAAAGjAIAAAM2cHgBc/3//4X///8JmQEAAAaPAgAABDE2cHgBcP3//4X///8JnAEAAAaSAgAABDEwcHgBbf3//4X///8JnwEAAAaVAgAABDE3cHgBav3//4X///8JogEAAAaYAgAABDM5cHgBZ/3//4X///8JpQEAAAabAgAABDE3cHgBZP3//4X///8JqAEAAAmkAAAAAWH9//+F////CasBAAAGoQIAAAEzB24AAAAAAQAAABQAAAAD5AFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlWYWx1ZVBhaXJgMltbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XSxbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0BXv3//4X///8JcgEAAAakAgAABGF0w6kBW/3//4X///8JdQEAAAmPAAAAAVj9//+F////CXgBAAAJeQEAAAFV/f//hf///wl7AQAACXwBAAABUv3//4X///8JfgEAAAl/AQAAAU/9//+F////CYEBAAAGswIAAAMwcHgBTP3//4X///8GtQIAAAtBbmNob3IuTGVmdAoBSv3//4X///8GtwIAAApBbmNob3IuVG9wCgFI/f//hf///wa5AgAADEFuY2hvci5SaWdodAoBRv3//4X///8GuwIAAA1BbmNob3IuQm90dG9tCgFE/f//hf///wa9AgAADkFuY2hvci5DZW50ZXJICYkAAAABQf3//4X///8GwAIAAA5BbmNob3IuQ2VudGVyVgmJAAAAAT79//+F////CZYBAAAGxAIAAAUxODNweAE7/f//hf///wmZAQAABscCAAAEMTZweAE4/f//hf///wmcAQAABsoCAAAEMTBweAE1/f//hf///wmfAQAABs0CAAAEMTdweAEy/f//hf///wmiAQAABtACAAAEMjhweAEv/f//hf///wmlAQAABtMCAAAEMTdweAEs/f//hf///wmoAQAACaQAAAABKf3//4X///8JqwEAAAbZAgAAATQHcAAAAAABAAAADwAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQEm/f//hf///wbbAgAAC0FuY2hvci5MZWZ0CgEk/f//hf///wbdAgAACkFuY2hvci5Ub3AKASL9//+F////Bt8CAAAMQW5jaG9yLlJpZ2h0CgEg/f//hf///wbhAgAADUFuY2hvci5Cb3R0b20KAR79//+F////BuMCAAAOQW5jaG9yLkNlbnRlckgJiQAAAAEb/f//hf///wbmAgAADkFuY2hvci5DZW50ZXJWCYkAAAABGP3//4X///8JvgEAAAmPAAAAARX9//+F////CcEBAAAG7QIAAAUyMTBweAES/f//hf///wnEAQAABvACAAAEMTVweAEP/f//hf///wnHAQAABvMCAAAEMTBweAEM/f//hf///wnKAQAABvYCAAAEMTdweAEJ/f//hf///wnNAQAABvkCAAAFMTMwcHgBBv3//4X///8J0AEAAAb8AgAABDE3cHgBA/3//4X///8J0wEAAAmkAAAAAQD9//+F////CdYBAAAGAgMAAAEyB3IAAAAAAQAAAA8AAAAD5AFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlWYWx1ZVBhaXJgMltbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XSxbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0B/fz//4X///8GBAMAAAtBbmNob3IuTGVmdAYFAwAAATUB+vz//4X///8GBwMAAApBbmNob3IuVG9wCgH4/P//hf///wYJAwAADEFuY2hvci5SaWdodAYKAwAAATUB9fz//4X///8GDAMAAA1BbmNob3IuQm90dG9tBg0DAAABNQHy/P//hf///wYPAwAADkFuY2hvci5DZW50ZXJICYkAAAAB7/z//4X///8GEgMAAA5BbmNob3IuQ2VudGVyVgmJAAAAAez8//+F////BhUDAAAHVmlzaWJsZQmPAAAAAen8//+F////BhgDAAAETGVmdAYZAwAAAzVweAHm/P//hf///wYbAwAAA1RvcAYcAwAABTMyN3B4AeP8//+F////Bh4DAAAITWluV2lkdGgGHwMAAAQyMHB4AeD8//+F////BiEDAAAJTWluSGVpZ2h0BiIDAAAEMTBweAHd/P//hf///wYkAwAABVdpZHRoBiUDAAAFNjEycHgB2vz//4X///8GJwMAAAZIZWlnaHQGKAMAAAQzNXB4Adf8//+F////BioDAAAMVHlwZVBvc2l0aW9uCaQAAAAB1Pz//4X///8GLQMAAAZaSW5kZXgGLgMAAAEyB3QAAAAAAQAAABEAAAAD5AFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlWYWx1ZVBhaXJgMltbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XSxbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0B0fz//4X///8GMAMAAARUZXh0CSIAAAABzvz//4X///8GMwMAAA5TdHlsZUNvbnRhaW5lcgmJAAAAAcv8//+F////BjYDAAALQW5jaG9yLkxlZnQKAcn8//+F////BjgDAAAKQW5jaG9yLlRvcAoBx/z//4X///8GOgMAAAxBbmNob3IuUmlnaHQKAcX8//+F////BjwDAAANQW5jaG9yLkJvdHRvbQoBw/z//4X///8GPgMAAA5BbmNob3IuQ2VudGVySAmJAAAAAcD8//+F////BkEDAAAOQW5jaG9yLkNlbnRlclYJiQAAAAG9/P//hf///wZEAwAAB1Zpc2libGUJjwAAAAG6/P//hf///wZHAwAABExlZnQGSAMAAAMwcHgBt/z//4X///8GSgMAAANUb3AGSwMAAAMwcHgBtPz//4X///8GTQMAAAhNaW5XaWR0aAZOAwAABDEwcHgBsfz//4X///8GUAMAAAlNaW5IZWlnaHQGUQMAAAQxMHB4Aa78//+F////BlMDAAAFV2lkdGgGVAMAAAUzMDZweAGr/P//hf///wZWAwAABkhlaWdodAZXAwAABDM1cHgBqPz//4X///8GWQMAAAxUeXBlUG9zaXRpb24JpAAAAAGl/P//hf///wZcAwAABlpJbmRleAZdAwAAATEHdgAAAAABAAAAEgAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQGi/P//hf///wk/AQAABmADAAAQQ29uZmlybWFyIEZpbHRybwGf/P//hf///wlCAQAACUMBAAABnPz//4X///8JRQEAAAlDAQAAAZn8//+F////BmgDAAALQW5jaG9yLkxlZnQGaQMAAAE1AZb8//+F////BmsDAAAKQW5jaG9yLlRvcAoBlPz//4X///8GbQMAAAxBbmNob3IuUmlnaHQGbgMAAAE1AZH8//+F////BnADAAANQW5jaG9yLkJvdHRvbQZxAwAAATUBjvz//4X///8GcwMAAA5BbmNob3IuQ2VudGVySAmJAAAAAYv8//+F////BnYDAAAOQW5jaG9yLkNlbnRlclYJiQAAAAGI/P//hf///wlXAQAACY8AAAABhfz//4X///8JWgEAAAZ9AwAAAzVweAGC/P//hf///wldAQAABoADAAADNXB4AX/8//+F////CWABAAAGgwMAAAQxMHB4AXz8//+F////CWMBAAAGhgMAAAQyNXB4AXn8//+F////CWYBAAAGiQMAAAUyOTZweAF2/P//hf///wlpAQAABowDAAAEMjVweAFz/P//hf///wlsAQAACaQAAAABcPz//4X///8JbwEAAAaSAwAAATEHeAAAAAABAAAAEQAAAAPkAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQFt/P//hf///wkwAwAACSIAAAABavz//4X///8JMwMAAAmJAAAAAWf8//+F////BpoDAAALQW5jaG9yLkxlZnQKAWX8//+F////BpwDAAAKQW5jaG9yLlRvcAoBY/z//4X///8GngMAAAxBbmNob3IuUmlnaHQKAWH8//+F////BqADAAANQW5jaG9yLkJvdHRvbQoBX/z//4X///8GogMAAA5BbmNob3IuQ2VudGVySAmJAAAAAVz8//+F////BqUDAAAOQW5jaG9yLkNlbnRlclYJiQAAAAFZ/P//hf///wlEAwAACY8AAAABVvz//4X///8JRwMAAAasAwAABTMwNnB4AVP8//+F////CUoDAAAGrwMAAAMwcHgBUPz//4X///8JTQMAAAayAwAABDEwcHgBTfz//4X///8JUAMAAAa1AwAABDEwcHgBSvz//4X///8JUwMAAAa4AwAABTMwNnB4AUf8//+F////CVYDAAAGuwMAAAQzNXB4AUT8//+F////CVkDAAAJpAAAAAFB/P//hf///wlcAwAABsEDAAABMgd6AAAAAAEAAAASAAAAA+QBU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuS2V5VmFsdWVQYWlyYDJbW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV0sW1N5c3RlbS5TdHJpbmcsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAT78//+F////CT8BAAAGxAMAAAhDYW5jZWxhcgE7/P//hf///wlCAQAACUMBAAABOPz//4X///8JRQEAAAlDAQAAATX8//+F////BswDAAALQW5jaG9yLkxlZnQGzQMAAAE1ATL8//+F////Bs8DAAAKQW5jaG9yLlRvcAoBMPz//4X///8G0QMAAAxBbmNob3IuUmlnaHQG0gMAAAE1AS38//+F////BtQDAAANQW5jaG9yLkJvdHRvbQbVAwAAATUBKvz//4X///8G1wMAAA5BbmNob3IuQ2VudGVySAmJAAAAASf8//+F////BtoDAAAOQW5jaG9yLkNlbnRlclYJiQAAAAEk/P//hf///wlXAQAACY8AAAABIfz//4X///8JWgEAAAbhAwAAAzVweAEe/P//hf///wldAQAABuQDAAADNXB4ARv8//+F////CWABAAAG5wMAAAQxMHB4ARj8//+F////CWMBAAAG6gMAAAQyNXB4ARX8//+F////CWYBAAAG7QMAAAUyOTZweAES/P//hf///wlpAQAABvADAAAEMjVweAEP/P//hf///wlsAQAACaQAAAABDPz//4X///8JbwEAAAb2AwAAATELAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            this.Layouts.NoSave = true;
            this.LayoutCurrent  = @"Menor que 950";
            this.Visible  = false;
            this.Left  =  new Ara2.Components.AraDistance(@"0px");
            this.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.MinHeight  =  new Ara2.Components.AraDistance(@"10px");
            this.Width  =  new Ara2.Components.AraDistance(@"622px");
            this.Height  =  new Ara2.Components.AraDistance(@"367px");
            #endregion
            
            
            #region TabsTiposFiltro
            this.TabsTiposFiltro = new Ara2.Components.AraTabs(this);

            this.TabsTiposFiltro.Name = "TabsTiposFiltro";
            this.TabsTiposFiltro.Anchor.Left  = 5;
            this.TabsTiposFiltro.Anchor.Top  = 5;
            this.TabsTiposFiltro.Anchor.Right  = 5;
            this.TabsTiposFiltro.Anchor.Bottom  = 50;
            this.TabsTiposFiltro.Left  =  new Ara2.Components.AraDistance(@"5px");
            this.TabsTiposFiltro.Top  =  new Ara2.Components.AraDistance(@"5px");
            this.TabsTiposFiltro.MinWidth  =  new Ara2.Components.AraDistance(@"40px");
            this.TabsTiposFiltro.MinHeight  =  new Ara2.Components.AraDistance(@"40px");
            this.TabsTiposFiltro.Width  =  new Ara2.Components.AraDistance(@"612px");
            this.TabsTiposFiltro.Height  =  new Ara2.Components.AraDistance(@"312px");
            this.TabsTiposFiltro.ZIndex  = 1;
            #endregion
            #region A0O295
            this.A0O295 = new Ara2.Components.AraSplitContainers(this);

            this.A0O295.Name = "A0O295";
            this.A0O295.Anchor.Left  = 5;
            this.A0O295.Anchor.Right  = 5;
            this.A0O295.Anchor.Bottom  = 5;
            this.A0O295.Left  =  new Ara2.Components.AraDistance(@"5px");
            this.A0O295.Top  =  new Ara2.Components.AraDistance(@"327px");
            this.A0O295.MinWidth  =  new Ara2.Components.AraDistance(@"20px");
            this.A0O295.MinHeight  =  new Ara2.Components.AraDistance(@"10px");
            this.A0O295.Width  =  new Ara2.Components.AraDistance(@"612px");
            this.A0O295.Height  =  new Ara2.Components.AraDistance(@"35px");
            this.A0O295.ZIndex  = 2;
            #endregion
            #region TabSimples
            this.TabSimples = new Ara2.Components.AraTab(this.TabsTiposFiltro);

            this.TabSimples.Name = "TabSimples";
            this.TabSimples.Caption  = @"Filtro Simples";
            this.TabSimples.Pos  = 0;
            this.TabSimples.TabActive  = true;
            this.TabSimples.Anchor.Left  = 1;
            this.TabSimples.Anchor.Top  = 41;
            this.TabSimples.Anchor.Right  = 1;
            this.TabSimples.Anchor.Bottom  = 1;
            this.TabSimples.Left  =  new Ara2.Components.AraDistance(@"1px");
            this.TabSimples.Top  =  new Ara2.Components.AraDistance(@"41px");
            this.TabSimples.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.TabSimples.MinHeight  =  new Ara2.Components.AraDistance(@"10px");
            this.TabSimples.Width  =  new Ara2.Components.AraDistance(@"610px");
            this.TabSimples.Height  =  new Ara2.Components.AraDistance(@"270px");
            this.TabSimples.ZIndex  = 1;
            #endregion
            #region TabMultiplos
            this.TabMultiplos = new Ara2.Components.AraTab(this.TabsTiposFiltro);

            this.TabMultiplos.Name = "TabMultiplos";
            this.TabMultiplos.Caption  = @"Filtro Múltiplo";
            this.TabMultiplos.Pos  = 2;
            this.TabMultiplos.Anchor.Left  = 1;
            this.TabMultiplos.Anchor.Top  = 41;
            this.TabMultiplos.Anchor.Right  = 1;
            this.TabMultiplos.Anchor.Bottom  = 1;
            this.TabMultiplos.Left  =  new Ara2.Components.AraDistance(@"1px");
            this.TabMultiplos.Top  =  new Ara2.Components.AraDistance(@"41px");
            this.TabMultiplos.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.TabMultiplos.MinHeight  =  new Ara2.Components.AraDistance(@"10px");
            this.TabMultiplos.Width  =  new Ara2.Components.AraDistance(@"610px");
            this.TabMultiplos.Height  =  new Ara2.Components.AraDistance(@"270px");
            this.TabMultiplos.ZIndex  = 2;
            #endregion
            #region tabIntervaloDatas
            this.tabIntervaloDatas = new Ara2.Components.AraTab(this.TabsTiposFiltro);

            this.tabIntervaloDatas.Name = "tabIntervaloDatas";
            this.tabIntervaloDatas.Caption  = @"Intervalo Simples";
            this.tabIntervaloDatas.Pos  = 1;
            this.tabIntervaloDatas.Anchor.Left  = 1;
            this.tabIntervaloDatas.Anchor.Top  = 41;
            this.tabIntervaloDatas.Anchor.Right  = 1;
            this.tabIntervaloDatas.Anchor.Bottom  = 1;
            this.tabIntervaloDatas.Left  =  new Ara2.Components.AraDistance(@"1px");
            this.tabIntervaloDatas.Top  =  new Ara2.Components.AraDistance(@"41px");
            this.tabIntervaloDatas.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.tabIntervaloDatas.MinHeight  =  new Ara2.Components.AraDistance(@"10px");
            this.tabIntervaloDatas.Width  =  new Ara2.Components.AraDistance(@"610px");
            this.tabIntervaloDatas.Height  =  new Ara2.Components.AraDistance(@"270px");
            this.tabIntervaloDatas.ZIndex  = 3;
            #endregion
            #region GridFiltroSimples
            this.GridFiltroSimples = new Ara2.Grid.AraGridSearchLinq(this.TabSimples);

            this.GridFiltroSimples.Name = "GridFiltroSimples";
            this.GridFiltroSimples.Anchor.Left  = 5;
            this.GridFiltroSimples.Anchor.Top  = 5;
            this.GridFiltroSimples.Anchor.Right  = 5;
            this.GridFiltroSimples.Anchor.Bottom  = 5;
            this.GridFiltroSimples.Left  =  new Ara2.Components.AraDistance(@"5px");
            this.GridFiltroSimples.Top  =  new Ara2.Components.AraDistance(@"5px");
            this.GridFiltroSimples.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.GridFiltroSimples.MinHeight  =  new Ara2.Components.AraDistance(@"10px");
            this.GridFiltroSimples.Width  =  new Ara2.Components.AraDistance(@"600px");
            this.GridFiltroSimples.Height  =  new Ara2.Components.AraDistance(@"260px");
            this.GridFiltroSimples.ZIndex  = 1;
            this.GridFiltroSimples.GetQuery  += GridFiltroSimples_GetQuery;
            this.GridFiltroSimples.ReturnSearch  += GridFiltroSimples_ReturnSearch;
            #endregion
            #region A0O264
            this.A0O264 = new Ara2.Components.AraLabel(this.TabMultiplos);

            this.A0O264.Name = "A0O264";
            this.A0O264.Text  = @"<b>Condição:</b> <small> (Ex: ""= 01/01/2013"" ou ""> 20/12/2013"" ou ""< 20/12/2013"")</small>";
            this.A0O264.Left  =  new Ara2.Components.AraDistance(@"3px");
            this.A0O264.Top  =  new Ara2.Components.AraDistance(@"6px");
            this.A0O264.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.A0O264.MinHeight  =  new Ara2.Components.AraDistance(@"17px");
            this.A0O264.Width  =  new Ara2.Components.AraDistance(@"425px");
            this.A0O264.Height  =  new Ara2.Components.AraDistance(@"17px");
            this.A0O264.ZIndex  = 1;
            #endregion
            #region bAdicionarAoFiltro
            this.bAdicionarAoFiltro = new Ara2.Components.AraButton(this.TabMultiplos);

            this.bAdicionarAoFiltro.Name = "bAdicionarAoFiltro";
            this.bAdicionarAoFiltro.Text  = @"Ad. Filtro";
            this.bAdicionarAoFiltro.Anchor.Right  = 5;
            this.bAdicionarAoFiltro.Left  =  new Ara2.Components.AraDistance(@"505px");
            this.bAdicionarAoFiltro.Top  =  new Ara2.Components.AraDistance(@"25px");
            this.bAdicionarAoFiltro.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.bAdicionarAoFiltro.MinHeight  =  new Ara2.Components.AraDistance(@"25px");
            this.bAdicionarAoFiltro.Width  =  new Ara2.Components.AraDistance(@"100px");
            this.bAdicionarAoFiltro.Height  =  new Ara2.Components.AraDistance(@"25px");
            this.bAdicionarAoFiltro.ZIndex  = 2;
            this.bAdicionarAoFiltro.Click  += bAdicionarAoFiltro_Click;
            #endregion
            #region txtCondicao
            this.txtCondicao = new Ara2.Components.AraTextBox(this.TabMultiplos);

            this.txtCondicao.Name = "txtCondicao";
            this.txtCondicao.Anchor.Left  = 5;
            this.txtCondicao.Anchor.Right  = 120;
            this.txtCondicao.Left  =  new Ara2.Components.AraDistance(@"5px");
            this.txtCondicao.Top  =  new Ara2.Components.AraDistance(@"29px");
            this.txtCondicao.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.txtCondicao.MinHeight  =  new Ara2.Components.AraDistance(@"17px");
            this.txtCondicao.Width  =  new Ara2.Components.AraDistance(@"485px");
            this.txtCondicao.Height  =  new Ara2.Components.AraDistance(@"17px");
            this.txtCondicao.ZIndex  = 3;
            #endregion
            #region lFiltro
            this.lFiltro = new Ara2.Components.AraLabel(this.TabMultiplos);

            this.lFiltro.Name = "lFiltro";
            this.lFiltro.Text  = @"<b>Filtrando por:</b>";
            this.lFiltro.TextVAlignValue  =  new Ara2.Components.AraDistance(@"0px");
            this.lFiltro.Anchor.Left  = 5;
            this.lFiltro.Anchor.Top  = 60;
            this.lFiltro.Anchor.Right  = 5;
            this.lFiltro.Anchor.Bottom  = 5;
            this.lFiltro.Left  =  new Ara2.Components.AraDistance(@"5px");
            this.lFiltro.Top  =  new Ara2.Components.AraDistance(@"60px");
            this.lFiltro.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.lFiltro.MinHeight  =  new Ara2.Components.AraDistance(@"17px");
            this.lFiltro.Width  =  new Ara2.Components.AraDistance(@"600px");
            this.lFiltro.Height  =  new Ara2.Components.AraDistance(@"205px");
            this.lFiltro.ZIndex  = 4;
            #endregion
            #region txtDataIni
            this.txtDataIni = new Ara2.Components.AraTextBox(this.tabIntervaloDatas);

            this.txtDataIni.Name = "txtDataIni";
            this.txtDataIni.Left  =  new Ara2.Components.AraDistance(@"45px");
            this.txtDataIni.Top  =  new Ara2.Components.AraDistance(@"15px");
            this.txtDataIni.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.txtDataIni.MinHeight  =  new Ara2.Components.AraDistance(@"17px");
            this.txtDataIni.Width  =  new Ara2.Components.AraDistance(@"130px");
            this.txtDataIni.Height  =  new Ara2.Components.AraDistance(@"17px");
            this.txtDataIni.ZIndex  = 1;
            #endregion
            #region txtDataFim
            this.txtDataFim = new Ara2.Components.AraTextBox(this.tabIntervaloDatas);

            this.txtDataFim.Name = "txtDataFim";
            this.txtDataFim.Left  =  new Ara2.Components.AraDistance(@"210px");
            this.txtDataFim.Top  =  new Ara2.Components.AraDistance(@"15px");
            this.txtDataFim.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.txtDataFim.MinHeight  =  new Ara2.Components.AraDistance(@"17px");
            this.txtDataFim.Width  =  new Ara2.Components.AraDistance(@"130px");
            this.txtDataFim.Height  =  new Ara2.Components.AraDistance(@"17px");
            this.txtDataFim.ZIndex  = 2;
            #endregion
            #region A0O195
            this.A0O195 = new Ara2.Components.AraLabel(this.tabIntervaloDatas);

            this.A0O195.Name = "A0O195";
            this.A0O195.Text  = @"Data:";
            this.A0O195.Left  =  new Ara2.Components.AraDistance(@"6px");
            this.A0O195.Top  =  new Ara2.Components.AraDistance(@"16px");
            this.A0O195.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.A0O195.MinHeight  =  new Ara2.Components.AraDistance(@"17px");
            this.A0O195.Width  =  new Ara2.Components.AraDistance(@"39px");
            this.A0O195.Height  =  new Ara2.Components.AraDistance(@"17px");
            this.A0O195.ZIndex  = 3;
            #endregion
            #region A0O206
            this.A0O206 = new Ara2.Components.AraLabel(this.tabIntervaloDatas);

            this.A0O206.Name = "A0O206";
            this.A0O206.Text  = @"até";
            this.A0O206.TextVAlignValue  =  new Ara2.Components.AraDistance(@"0px");
            this.A0O206.Left  =  new Ara2.Components.AraDistance(@"183px");
            this.A0O206.Top  =  new Ara2.Components.AraDistance(@"16px");
            this.A0O206.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.A0O206.MinHeight  =  new Ara2.Components.AraDistance(@"17px");
            this.A0O206.Width  =  new Ara2.Components.AraDistance(@"28px");
            this.A0O206.Height  =  new Ara2.Components.AraDistance(@"17px");
            this.A0O206.ZIndex  = 4;
            #endregion
            #region A0O301
            this.A0O301 = new Ara2.Components.AraSplitContainer(this.A0O295);

            this.A0O301.Name = "A0O301";
            this.A0O301.Percent  = 50;
            this.A0O301.Left  =  new Ara2.Components.AraDistance(@"0px");
            this.A0O301.Top  =  new Ara2.Components.AraDistance(@"0px");
            this.A0O301.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.A0O301.MinHeight  =  new Ara2.Components.AraDistance(@"10px");
            this.A0O301.Width  =  new Ara2.Components.AraDistance(@"306px");
            this.A0O301.Height  =  new Ara2.Components.AraDistance(@"35px");
            this.A0O301.ZIndex  = 1;
            #endregion
            #region A0O311
            this.A0O311 = new Ara2.Components.AraSplitContainer(this.A0O295);

            this.A0O311.Name = "A0O311";
            this.A0O311.Percent  = 50;
            this.A0O311.Left  =  new Ara2.Components.AraDistance(@"306px");
            this.A0O311.Top  =  new Ara2.Components.AraDistance(@"0px");
            this.A0O311.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.A0O311.MinHeight  =  new Ara2.Components.AraDistance(@"10px");
            this.A0O311.Width  =  new Ara2.Components.AraDistance(@"306px");
            this.A0O311.Height  =  new Ara2.Components.AraDistance(@"35px");
            this.A0O311.ZIndex  = 2;
            #endregion
            #region bConfirmar
            this.bConfirmar = new Ara2.Components.AraButton(this.A0O301);

            this.bConfirmar.Name = "bConfirmar";
            this.bConfirmar.Text  = @"Confirmar Filtro";
            this.bConfirmar.Anchor.Left  = 5;
            this.bConfirmar.Anchor.Right  = 5;
            this.bConfirmar.Anchor.Bottom  = 5;
            this.bConfirmar.Left  =  new Ara2.Components.AraDistance(@"5px");
            this.bConfirmar.Top  =  new Ara2.Components.AraDistance(@"5px");
            this.bConfirmar.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.bConfirmar.MinHeight  =  new Ara2.Components.AraDistance(@"25px");
            this.bConfirmar.Width  =  new Ara2.Components.AraDistance(@"296px");
            this.bConfirmar.Height  =  new Ara2.Components.AraDistance(@"25px");
            this.bConfirmar.ZIndex  = 1;
            this.bConfirmar.Click  += bConfirmar_Click;
            #endregion
            #region bCancelar
            this.bCancelar = new Ara2.Components.AraButton(this.A0O311);

            this.bCancelar.Name = "bCancelar";
            this.bCancelar.Text  = @"Cancelar";
            this.bCancelar.Anchor.Left  = 5;
            this.bCancelar.Anchor.Right  = 5;
            this.bCancelar.Anchor.Bottom  = 5;
            this.bCancelar.Left  =  new Ara2.Components.AraDistance(@"5px");
            this.bCancelar.Top  =  new Ara2.Components.AraDistance(@"5px");
            this.bCancelar.MinWidth  =  new Ara2.Components.AraDistance(@"10px");
            this.bCancelar.MinHeight  =  new Ara2.Components.AraDistance(@"25px");
            this.bCancelar.Width  =  new Ara2.Components.AraDistance(@"296px");
            this.bCancelar.Height  =  new Ara2.Components.AraDistance(@"25px");
            this.bCancelar.ZIndex  = 1;
            this.bCancelar.Click  += bCancelar_Click;
            #endregion
            
            
            #region Layouts Reander
            this.Layouts.Render();
            #endregion
            #endregion
        } 
    } 
} 
